namespace UnityEngine.Purchasing
{
	public enum StoreSpecificPurchaseErrorCode
	{
		SKErrorUnknown = 0,
		SKErrorClientInvalid = 1,
		SKErrorPaymentCancelled = 2,
		SKErrorPaymentInvalid = 3,
		SKErrorPaymentNotAllowed = 4,
		SKErrorStoreProductNotAvailable = 5,
		SKErrorCloudServicePermissionDenied = 6,
		SKErrorCloudServiceNetworkConnectionFailed = 7,
		SKErrorCloudServiceRevoked = 8,
		BILLING_RESPONSE_RESULT_OK = 9,
		BILLING_RESPONSE_RESULT_USER_CANCELED = 10,
		BILLING_RESPONSE_RESULT_SERVICE_UNAVAILABLE = 11,
		BILLING_RESPONSE_RESULT_BILLING_UNAVAILABLE = 12,
		BILLING_RESPONSE_RESULT_ITEM_UNAVAILABLE = 13,
		BILLING_RESPONSE_RESULT_DEVELOPER_ERROR = 14,
		BILLING_RESPONSE_RESULT_ERROR = 15,
		BILLING_RESPONSE_RESULT_ITEM_ALREADY_OWNED = 16,
		BILLING_RESPONSE_RESULT_ITEM_NOT_OWNED = 17,
		IABHELPER_ERROR_BASE = 18,
		IABHELPER_REMOTE_EXCEPTION = 19,
		IABHELPER_BAD_RESPONSE = 20,
		IABHELPER_VERIFICATION_FAILED = 21,
		IABHELPER_SEND_INTENT_FAILED = 22,
		IABHELPER_USER_CANCELLED = 23,
		IABHELPER_UNKNOWN_PURCHASE_RESPONSE = 24,
		IABHELPER_MISSING_TOKEN = 25,
		IABHELPER_UNKNOWN_ERROR = 26,
		IABHELPER_SUBSCRIPTIONS_NOT_AVAILABLE = 27,
		IABHELPER_INVALID_CONSUMPTION = 28,
		Unknown = 29
	}
}
