namespace NBidi
{
	public abstract class BidiCharacterMirrorResolver
	{
		public static char GetBidiCharacterMirror(char c)
		{
			switch (c)
			{
			case '(':
				return ')';
			case ')':
				return '(';
			case '<':
				return '>';
			case '>':
				return '<';
			case '[':
				return ']';
			case ']':
				return '[';
			case '{':
				return '}';
			case '}':
				return '{';
			case '«':
				return '»';
			case '»':
				return '«';
			case '༺':
				return '༻';
			case '༻':
				return '༺';
			case '༼':
				return '༽';
			case '༽':
				return '༼';
			case '᚛':
				return '᚜';
			case '᚜':
				return '᚛';
			case '‹':
				return '›';
			case '›':
				return '‹';
			case '⁅':
				return '⁆';
			case '⁆':
				return '⁅';
			case '⁽':
				return '⁾';
			case '⁾':
				return '⁽';
			case '₍':
				return '₎';
			case '₎':
				return '₍';
			case '∈':
				return '∋';
			case '∉':
				return '∌';
			case '∊':
				return '∍';
			case '∋':
				return '∈';
			case '∌':
				return '∉';
			case '∍':
				return '∊';
			case '∕':
				return '⧵';
			case '∼':
				return '∽';
			case '∽':
				return '∼';
			case '≃':
				return '⋍';
			case '≒':
				return '≓';
			case '≓':
				return '≒';
			case '≔':
				return '≕';
			case '≕':
				return '≔';
			case '≤':
				return '≥';
			case '≥':
				return '≤';
			case '≦':
				return '≧';
			case '≧':
				return '≦';
			case '≨':
				return '≩';
			case '≩':
				return '≨';
			case '≪':
				return '≫';
			case '≫':
				return '≪';
			case '≮':
				return '≯';
			case '≯':
				return '≮';
			case '≰':
				return '≱';
			case '≱':
				return '≰';
			case '≲':
				return '≳';
			case '≳':
				return '≲';
			case '≴':
				return '≵';
			case '≵':
				return '≴';
			case '≶':
				return '≷';
			case '≷':
				return '≶';
			case '≸':
				return '≹';
			case '≹':
				return '≸';
			case '≺':
				return '≻';
			case '≻':
				return '≺';
			case '≼':
				return '≽';
			case '≽':
				return '≼';
			case '≾':
				return '≿';
			case '≿':
				return '≾';
			case '⊀':
				return '⊁';
			case '⊁':
				return '⊀';
			case '⊂':
				return '⊃';
			case '⊃':
				return '⊂';
			case '⊄':
				return '⊅';
			case '⊅':
				return '⊄';
			case '⊆':
				return '⊇';
			case '⊇':
				return '⊆';
			case '⊈':
				return '⊉';
			case '⊉':
				return '⊈';
			case '⊊':
				return '⊋';
			case '⊋':
				return '⊊';
			case '⊏':
				return '⊐';
			case '⊐':
				return '⊏';
			case '⊑':
				return '⊒';
			case '⊒':
				return '⊑';
			case '⊘':
				return '⦸';
			case '⊢':
				return '⊣';
			case '⊣':
				return '⊢';
			case '⊦':
				return '⫞';
			case '⊨':
				return '⫤';
			case '⊩':
				return '⫣';
			case '⊫':
				return '⫥';
			case '⊰':
				return '⊱';
			case '⊱':
				return '⊰';
			case '⊲':
				return '⊳';
			case '⊳':
				return '⊲';
			case '⊴':
				return '⊵';
			case '⊵':
				return '⊴';
			case '⊶':
				return '⊷';
			case '⊷':
				return '⊶';
			case '⋉':
				return '⋊';
			case '⋊':
				return '⋉';
			case '⋋':
				return '⋌';
			case '⋌':
				return '⋋';
			case '⋍':
				return '≃';
			case '⋐':
				return '⋑';
			case '⋑':
				return '⋐';
			case '⋖':
				return '⋗';
			case '⋗':
				return '⋖';
			case '⋘':
				return '⋙';
			case '⋙':
				return '⋘';
			case '⋚':
				return '⋛';
			case '⋛':
				return '⋚';
			case '⋜':
				return '⋝';
			case '⋝':
				return '⋜';
			case '⋞':
				return '⋟';
			case '⋟':
				return '⋞';
			case '⋠':
				return '⋡';
			case '⋡':
				return '⋠';
			case '⋢':
				return '⋣';
			case '⋣':
				return '⋢';
			case '⋤':
				return '⋥';
			case '⋥':
				return '⋤';
			case '⋦':
				return '⋧';
			case '⋧':
				return '⋦';
			case '⋨':
				return '⋩';
			case '⋩':
				return '⋨';
			case '⋪':
				return '⋫';
			case '⋫':
				return '⋪';
			case '⋬':
				return '⋭';
			case '⋭':
				return '⋬';
			case '⋰':
				return '⋱';
			case '⋱':
				return '⋰';
			case '⋲':
				return '⋺';
			case '⋳':
				return '⋻';
			case '⋴':
				return '⋼';
			case '⋶':
				return '⋽';
			case '⋷':
				return '⋾';
			case '⋺':
				return '⋲';
			case '⋻':
				return '⋳';
			case '⋼':
				return '⋴';
			case '⋽':
				return '⋶';
			case '⋾':
				return '⋷';
			case '⌈':
				return '⌉';
			case '⌉':
				return '⌈';
			case '⌊':
				return '⌋';
			case '⌋':
				return '⌊';
			case '〈':
				return '〉';
			case '〉':
				return '〈';
			case '❨':
				return '❩';
			case '❩':
				return '❨';
			case '❪':
				return '❫';
			case '❫':
				return '❪';
			case '❬':
				return '❭';
			case '❭':
				return '❬';
			case '❮':
				return '❯';
			case '❯':
				return '❮';
			case '❰':
				return '❱';
			case '❱':
				return '❰';
			case '❲':
				return '❳';
			case '❳':
				return '❲';
			case '❴':
				return '❵';
			case '❵':
				return '❴';
			case '⟃':
				return '⟄';
			case '⟄':
				return '⟃';
			case '⟅':
				return '⟆';
			case '⟆':
				return '⟅';
			case '⟈':
				return '⟉';
			case '⟉':
				return '⟈';
			case '⟕':
				return '⟖';
			case '⟖':
				return '⟕';
			case '⟝':
				return '⟞';
			case '⟞':
				return '⟝';
			case '⟢':
				return '⟣';
			case '⟣':
				return '⟢';
			case '⟤':
				return '⟥';
			case '⟥':
				return '⟤';
			case '⟦':
				return '⟧';
			case '⟧':
				return '⟦';
			case '⟨':
				return '⟩';
			case '⟩':
				return '⟨';
			case '⟪':
				return '⟫';
			case '⟫':
				return '⟪';
			case '⟬':
				return '⟭';
			case '⟭':
				return '⟬';
			case '⟮':
				return '⟯';
			case '⟯':
				return '⟮';
			case '⦃':
				return '⦄';
			case '⦄':
				return '⦃';
			case '⦅':
				return '⦆';
			case '⦆':
				return '⦅';
			case '⦇':
				return '⦈';
			case '⦈':
				return '⦇';
			case '⦉':
				return '⦊';
			case '⦊':
				return '⦉';
			case '⦋':
				return '⦌';
			case '⦌':
				return '⦋';
			case '⦍':
				return '⦐';
			case '⦎':
				return '⦏';
			case '⦏':
				return '⦎';
			case '⦐':
				return '⦍';
			case '⦑':
				return '⦒';
			case '⦒':
				return '⦑';
			case '⦓':
				return '⦔';
			case '⦔':
				return '⦓';
			case '⦕':
				return '⦖';
			case '⦖':
				return '⦕';
			case '⦗':
				return '⦘';
			case '⦘':
				return '⦗';
			case '⦸':
				return '⊘';
			case '⧀':
				return '⧁';
			case '⧁':
				return '⧀';
			case '⧄':
				return '⧅';
			case '⧅':
				return '⧄';
			case '⧏':
				return '⧐';
			case '⧐':
				return '⧏';
			case '⧑':
				return '⧒';
			case '⧒':
				return '⧑';
			case '⧔':
				return '⧕';
			case '⧕':
				return '⧔';
			case '⧘':
				return '⧙';
			case '⧙':
				return '⧘';
			case '⧚':
				return '⧛';
			case '⧛':
				return '⧚';
			case '⧵':
				return '∕';
			case '⧸':
				return '⧹';
			case '⧹':
				return '⧸';
			case '⧼':
				return '⧽';
			case '⧽':
				return '⧼';
			case '⨫':
				return '⨬';
			case '⨬':
				return '⨫';
			case '⨭':
				return '⨮';
			case '⨮':
				return '⨭';
			case '⨴':
				return '⨵';
			case '⨵':
				return '⨴';
			case '⨼':
				return '⨽';
			case '⨽':
				return '⨼';
			case '⩤':
				return '⩥';
			case '⩥':
				return '⩤';
			case '⩹':
				return '⩺';
			case '⩺':
				return '⩹';
			case '⩽':
				return '⩾';
			case '⩾':
				return '⩽';
			case '⩿':
				return '⪀';
			case '⪀':
				return '⩿';
			case '⪁':
				return '⪂';
			case '⪂':
				return '⪁';
			case '⪃':
				return '⪄';
			case '⪄':
				return '⪃';
			case '⪋':
				return '⪌';
			case '⪌':
				return '⪋';
			case '⪑':
				return '⪒';
			case '⪒':
				return '⪑';
			case '⪓':
				return '⪔';
			case '⪔':
				return '⪓';
			case '⪕':
				return '⪖';
			case '⪖':
				return '⪕';
			case '⪗':
				return '⪘';
			case '⪘':
				return '⪗';
			case '⪙':
				return '⪚';
			case '⪚':
				return '⪙';
			case '⪛':
				return '⪜';
			case '⪜':
				return '⪛';
			case '⪡':
				return '⪢';
			case '⪢':
				return '⪡';
			case '⪦':
				return '⪧';
			case '⪧':
				return '⪦';
			case '⪨':
				return '⪩';
			case '⪩':
				return '⪨';
			case '⪪':
				return '⪫';
			case '⪫':
				return '⪪';
			case '⪬':
				return '⪭';
			case '⪭':
				return '⪬';
			case '⪯':
				return '⪰';
			case '⪰':
				return '⪯';
			case '⪳':
				return '⪴';
			case '⪴':
				return '⪳';
			case '⪻':
				return '⪼';
			case '⪼':
				return '⪻';
			case '⪽':
				return '⪾';
			case '⪾':
				return '⪽';
			case '⪿':
				return '⫀';
			case '⫀':
				return '⪿';
			case '⫁':
				return '⫂';
			case '⫂':
				return '⫁';
			case '⫃':
				return '⫄';
			case '⫄':
				return '⫃';
			case '⫅':
				return '⫆';
			case '⫆':
				return '⫅';
			case '⫍':
				return '⫎';
			case '⫎':
				return '⫍';
			case '⫏':
				return '⫐';
			case '⫐':
				return '⫏';
			case '⫑':
				return '⫒';
			case '⫒':
				return '⫑';
			case '⫓':
				return '⫔';
			case '⫔':
				return '⫓';
			case '⫕':
				return '⫖';
			case '⫖':
				return '⫕';
			case '⫞':
				return '⊦';
			case '⫣':
				return '⊩';
			case '⫤':
				return '⊨';
			case '⫥':
				return '⊫';
			case '⫬':
				return '⫭';
			case '⫭':
				return '⫬';
			case '⫷':
				return '⫸';
			case '⫸':
				return '⫷';
			case '⫹':
				return '⫺';
			case '⫺':
				return '⫹';
			case '⸂':
				return '⸃';
			case '⸃':
				return '⸂';
			case '⸄':
				return '⸅';
			case '⸅':
				return '⸄';
			case '⸉':
				return '⸊';
			case '⸊':
				return '⸉';
			case '⸌':
				return '⸍';
			case '⸍':
				return '⸌';
			case '⸜':
				return '⸝';
			case '⸝':
				return '⸜';
			case '⸠':
				return '⸡';
			case '⸡':
				return '⸠';
			case '⸢':
				return '⸣';
			case '⸣':
				return '⸢';
			case '⸤':
				return '⸥';
			case '⸥':
				return '⸤';
			case '⸦':
				return '⸧';
			case '⸧':
				return '⸦';
			case '⸨':
				return '⸩';
			case '⸩':
				return '⸨';
			case '〈':
				return '〉';
			case '〉':
				return '〈';
			case '《':
				return '》';
			case '》':
				return '《';
			case '「':
				return '」';
			case '」':
				return '「';
			case '『':
				return '』';
			case '』':
				return '『';
			case '【':
				return '】';
			case '】':
				return '【';
			case '〔':
				return '〕';
			case '〕':
				return '〔';
			case '〖':
				return '〗';
			case '〗':
				return '〖';
			case '〘':
				return '〙';
			case '〙':
				return '〘';
			case '〚':
				return '〛';
			case '〛':
				return '〚';
			case '﹙':
				return '﹚';
			case '﹚':
				return '﹙';
			case '﹛':
				return '﹜';
			case '﹜':
				return '﹛';
			case '﹝':
				return '﹞';
			case '﹞':
				return '﹝';
			case '﹤':
				return '﹥';
			case '﹥':
				return '﹤';
			case '（':
				return '）';
			case '）':
				return '（';
			case '＜':
				return '＞';
			case '＞':
				return '＜';
			case '［':
				return '］';
			case '］':
				return '［';
			case '｛':
				return '｝';
			case '｝':
				return '｛';
			case '｟':
				return '｠';
			case '｠':
				return '｟';
			case '｢':
				return '｣';
			case '｣':
				return '｢';
			default:
				return c;
			}
		}
	}
}
